// <auto-generated />
namespace RoslynTestingApp
{
    using System;

    /// <summary>
    /// test
    /// </summary>
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
}
