// <auto-generated />
namespace TradingSimulator.DataBase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0-preview8-19405-04")]
    public sealed partial class v1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v1));
        
        string IMigrationMetadata.Id
        {
            get { return "201908231738566_v1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
